name: 'Blackduck-scanner-report-generator'
description: 'It authenticate and download the blackduck scan report'
inputs:
  access-token:
    description: 'acess token used to authenticate the blackduck'
    required: true
outputs:
  report:
    description: 'This is the blackduck-scan report in json format'
runs:
  using: 'docker'
  image: 'Dockerfile'