name: 'blackduck scan'
description: 'it authenticate and gets black duck scan report'
inputs:
  token: 
    description: 'token to authenticate'
    required: true
  blackduck-log: 
    description: 'blackduck log'
    required: true
runs:
  using: "composite"
  steps: 
    - shell: bash
      run: |
        BASE_URL='https://blackduck.platform-services.services-platdev.x.gcpnp.anz'
        AUTHENTICATE='api/tokens/authenticate'
        curl --request POST --url https://blackduck.platform-services.services-platdev.x.gcpnp.anz/api/tokens/authenticate --header "Authorization: token ${{ inputs.token }}"