name: 'blackduck scan'
description: 'it authenticate and gets black duck scan report'
inputs:
  token: 
    description: 'token to authenticate'
    required: true
  blackduck-log: 
    description: 'blackduck log'
    required: true
runs:
  using: "composite"
  steps: 
    - shell: bash
      run: |
        BASE_URL='https://blackduck.platform-services.services-platdev.x.gcpnp.anz'
        AUTHENTICATE='api/tokens/authenticate'
        bearerToken=$(curl --request POST --url ${BASE_URL}/${AUTHENTICATE} --header "Authorization: token ${{ inputs.token }}" | jq -r '.bearerToken')
        grep '/components' ${{ inputs.blackduck-log }} | tee blackduck_urls.txt
        temp=$(egrep -o 'https?://[^ ]+' blackduck_urls.txt)
        urlsArray=($temp)
        curl --request GET --url ${urlsArray[0]}".json" --header "Authorization: Bearer ${bearerToken}"