name: 'blackduck scan'
description: 'it authenticate and gets black duck scan report'
inputs:
  token: 
    description: 'token to authenticate'
    required: true
  blackduck-log: 
    description: 'blackduck log'
    required: true
runs:
  using: "composite"
  steps: 
    - shell: bash
      run: echo ${{ inputs.blackduck-log }}
    - shell: bash
      run: echo token ${{ inputs.token }}
    - run: ${{ github.action_path }}/blackduck.sh
      id: report-id
      shell: bash
