name: Structural Tests
on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: get data for report
        run: curl https://jsonplaceholder.typicode.com/todos/1 | tee report.json
#      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
#        with:
#          version: '290.0.1'
#          project_id: ${{ secrets.PROJECT_ID }}
#          service_account_key: ${{ secrets.TOKEN }}
#          export_default_credentials: true
#      - run: gsutil cp report.json gs://services/
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.TOKEN }}
        with:
          args: cp report.json gs://demo-services/
          cli: gsutil
