name: Structural Tests
on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: actions/hello-world-docker-action@v2
        id: hello
        with:
          access-token: ${{ secrets.FABRIC_BLACKDUCK_SCAN_TOKEN }}
          url: https://blackduck.platform-services.services-platdev.x.gcpnp.anz/api/projects/2bf5dadf-770e-4dbb-a54c-a2e78c7d6a7c/versions/7c85d352-df94-4aa5-84cd-f90f8ccd4629/components.json
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The report was ${{ steps.hello.outputs.report }}"

#      - uses: actions-hub/gcloud@master
#        env:
#          PROJECT_ID: ${{ secrets.PROJECT_ID }}
#          APPLICATION_CREDENTIALS: ${{ secrets.TOKEN }}
#        with:
#          args: cp report.json gs://demo-services/
#          cli: gsutil
