name: Structural Tests
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        uses: instrumenta/conftest-actions@master
        with:
          files: ./debian9/Dockerfile
          output: json
#      - uses: ouzi-dev/commit-status-updater@v1.0.4
#        with:
#          status: "pending"
#          addHoldComment: "true"
#          pendingComment: "actions pending!"
#          successComment: "actions success!"
#          failComment: "actions failed!"
