name: Structural Tests
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      IMAGE: grafana
      VERSION: 7.1.2
      PLUGINS: grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,vonage-status-panel
      IMAGE_RENDERER: true
    steps:
      - uses: actions/checkout@v2

      - name: build image for grafana
        working-directory: grafana
        run: |
          docker build \
            --build-arg "GF_INSTALL_PLUGINS=${PLUGINS}" \
            --build-arg "GF_INSTALL_IMAGE_RENDERER_PLUGIN=${IMAGE_RENDERER}" \
            -t docker.pkg.github.com/anzx/fabric-images/grafana:${VERSION} \
            -t docker.pkg.github.com/anzx/fabric-images/grafana:latest \
            -t docker.pkg.github.com/anzx/fabric-images/${IMAGE}:latest .
  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    env:
      IMAGE: grafana
      VERSION: 7.1.2
      PLUGINS: grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,vonage-status-panel
      IMAGE_RENDERER: true
    steps:
      - name: Conftest for debain9 dockerfile
        uses: instrumenta/conftest-action@v0.4.0
        with:
          files: ./debian9/Dockerfile
      - name: Comment Test Coverage
        uses: AthleticNet/comment-test-coverage@1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: coverage/coverage-summary.json
          title: Karma Test Coverage