name: Structural Tests
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup conftest
        uses: ./.github/actions
        with:
          files: ./debian9/Dockerfile
 #        uses: instrumenta/conftest-action@v0.4.0
#      - name: test
#        run: conftest test ./debian9/Dockerfile
#        with:
#          files: ./debian9/Dockerfile