name: Structural Tests
on: [push]
jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      FILE: ./debian9/Dockerfile
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Execute Conftest Tests - Table Output
        id: conftest-table
        run: |
          result=$(docker run --rm --workdir /github/workspace \
            -v $(pwd):/github/workspace \
            instrumenta/conftest:v0.18.2 \
            test ${FILE} -o tap || exit 0)
          result="${result//'%'/'%25'}"
          result="${result//$'\n'/'%0A'}"
          result="${result//$'\r'/'%0D'}"
          echo $result
          echo "::set-output name=result::$result"
      - name: Execute Conftest Tests - Stdout Output
        id: conftest-stdout
        run: |
          result=$(docker run --rm --workdir /github/workspace \
            -v $(pwd):/github/workspace \
            instrumenta/conftest:v0.18.2 \
            test -o stdout -p debian9/ --all-namespaces namespaces/ --no-color || exit 0)
          result="${result//'%'/'%25'}"
          result="${result//$'\n'/'%0A'}"
          result="${result//$'\r'/'%0D'}"
          echo $result
          echo ::set-output name=result::$result
      - name: Post Results
        uses: unsplash/comment-on-pr@master
        if: ${{ always() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            ## Conftest Test Results
            ```
            ${{ steps.conftest-table.outputs.result }}
            ```
            ## Conftest Test Results
            ```
            ${{ steps.conftest-stdout.outputs.result }}
            ```

          check_for_duplicate_msg: false
