name: Structural Tests
on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: report downloader step
        uses: actions/blackduck-report-downloader
        with:
          token: ${{ secrets.FABRIC_BLACKDUCK_SCAN_TOKEN }}
#      - uses: actions-hub/gcloud@master
#        env:
#          PROJECT_ID: ${{ secrets.PROJECT_ID }}
#          APPLICATION_CREDENTIALS: ${{ secrets.TOKEN }}
#        with:
#          args: cp report.json gs://demo-services/
#          cli: gsutil
