name: Structural Tests
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  test(12/12):
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello Rohit!"
          echo "- in git!"
