name: Structural Tests
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello Rohit!"
          echo "- in git!"
