name: Structural Tests
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  test_data:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      - name: Test
        uses: skx/github-action-tester@master
      - run: |
          echo "Hello Rohit!"
          echo "- in git!"
