name: Structural Tests
on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: get data for report
        run: curl https://jsonplaceholder.typicode.com/todos/1 | tee report.json
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.TOKEN }}
        with:
          args: cp report.json gs://services/
          cli: gsutil