name: Structural Tests
on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: get data for report
        run: curl https://jsonplaceholder.typicode.com/todos/1 | tee report.json
      - name: Hello world action step
        uses: customGitAction/hello-world-docker-action@v1
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

#      - uses: actions-hub/gcloud@master
#        env:
#          PROJECT_ID: ${{ secrets.PROJECT_ID }}
#          APPLICATION_CREDENTIALS: ${{ secrets.TOKEN }}
#        with:
#          args: cp report.json gs://demo-services/
#          cli: gsutil
