name: Structural Tests
on: [push]
jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      FILE: ./debian9/Dockerfile
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: build container test image
        working-directory: .github/actions
        run: |
          docker build \
            -t container-structure-test:latest .
      - name: build image
        working-directory: debian9
        run: |
          docker build \
            --build-arg "GF_INSTALL_PLUGINS=${PLUGINS}" \
            --build-arg "GF_INSTALL_IMAGE_RENDERER_PLUGIN=${IMAGE_RENDERER}" \
            -t docker.pkg.github.com/anzx/container-test/${IMAGE}:latest .
      - name: test structure
        id: container-stdout
        run: |
          result=$(docker run --rm -v $(pwd):/test-config container-test:latest test --image docker.pkg.github.com/anzx/containerTest/${IMAGE}:latest --config ./grafna_structural_tests.yaml --no-color)
          result="${result//'%'/'%25'}"
          result="${result//$'\n'/'%0A'}"
          result="${result//$'\r'/'%0D'}"
          echo $result
          echo "::set-output name=result::$result"
      - name: Execute Conftest Tests - Table Output
        id: conftest-table
        run: |
          result=$(docker run --rm --workdir /github/workspace \
            -v $(pwd):/github/workspace \
            instrumenta/conftest:v0.18.2 \
            test ${FILE} -o tap || exit 0)
          result="${result//'%'/'%25'}"
          result="${result//$'\n'/'%0A'}"
          result="${result//$'\r'/'%0D'}"
          echo $result
          echo "::set-output name=result::$result"
      - name: Execute Conftest Tests - Stdout Output
        id: conftest-stdout
        run: |
          result=$(docker run --rm --workdir /github/workspace \
            -v $(pwd):/github/workspace \
            instrumenta/conftest:v0.18.2 \
            test ${FILE} --no-color || exit 0)
          result="${result//'%'/'%25'}"
          result="${result//$'\n'/'%0A'}"
          result="${result//$'\r'/'%0D'}"
          echo $result
          echo ::set-output name=result::$result
      - name: Post Results
        uses: unsplash/comment-on-pr@master
        if: ${{ always() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            ## Conftest Test Results
            ```
            ${{ steps.conftest-table.outputs.result }}
            ${{ steps.conftest-stdout.outputs.result }}
            ```
            ## container structure Test Results
            ```
            ${{ steps.container-stdout.outputs.result }}
            ```

          check_for_duplicate_msg: false
