name: Structural Tests
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ouzi-dev/commit-status-updater@v1.0.4
        with:
          status: "pending"
          addHoldComment: "true"
          pendingComment: "action pending!"
          successComment: "action success!"
          failComment: "action failed!"
