# This is a basic workflow to help you get started with Actions

name: Structural Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    name: Running structural tests 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      IMAGE: grafana
      VERSION: 7.1.2
      PLUGINS: grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,vonage-status-panel
      IMAGE_RENDERER: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: build
      working-directory: grafana
      run: |
        docker build \
          --build-arg "GF_INSTALL_PLUGINS=${PLUGINS}" \
          --build-arg "GF_INSTALL_IMAGE_RENDERER_PLUGIN=${IMAGE_RENDERER}" \
          -t docker.pkg.github.com/anzx/fabric-images/grafana:${VERSION} \
          -t docker.pkg.github.com/anzx/fabric-images/${IMAGE}:latest .

    # Runs a set of commands using the runners shell
    - name: install container structure test
      run: |
        curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && chmod +x container-structure-test-linux-amd64 && mkdir -p $HOME/bin && export PATH=$PATH:$HOME/bin && mv container-structure-test-linux-amd64 $HOME/bin/container-structure-test
        
    # Runs a set of commands using the runners shell
    - name: Run test 
      run: |
        container-structure-test test --image docker.pkg.github.com/anzx/fabric-images/${IMAGE}:latest --config ./grafna_structural_tests.yaml
